/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Modelo.Cartao;
import Modelo.Colecionador;
import Modelo.ColecionadorEncontrado;
import Modelo.Troca;
import static java.lang.Thread.sleep;

/**
 *
 * @author Bruno
 */
public class JanelaDadosTroca extends javax.swing.JDialog {

    Troca troca;

    /**
     * Creates new form JanelaAvisoTroca
     *
     * @param idTroca
     * @throws java.lang.InterruptedException
     */
    public JanelaDadosTroca(String idTroca) throws InterruptedException {
        initComponents();
        setModal(true);
        Colecionador logado = Colecionador.getInstancia();
        troca = logado.getTrocaQueSouParticipantePorId(idTroca);
        this.setTitle("Nova Solicitação - " + logado.getIdColecionador());
        Cartao cartaoRecebe = troca.getCartaoManda();
        Cartao cartaoManda = troca.getCartaoRecebe();
        ColecionadorEncontrado outroColecionador = logado.getUsuarioParticipantePorId(troca.getIdSolicitante());
        String textoTroca = "Trocar " + cartaoRecebe.getIdCartao() + " - " + cartaoRecebe.getLocal()
                + " por " + cartaoManda.getIdCartao() + " - " + cartaoManda.getLocal() + " com "
                + outroColecionador.getIdColecionador() + " - " + outroColecionador.getNome();
        txtTroca.setText(textoTroca);
        
        switch (troca.getSituacaoTroca()) {
            case 1:
                labelStatus.setForeground(new java.awt.Color(0, 102, 204));
                labelStatus.setText("Aguardando");
                break;
            case 2:
                labelStatus.setForeground(new java.awt.Color(0, 102, 204));
                labelStatus.setText("Aguardando");
                break;
            case 3:
                labelStatus.setForeground(new java.awt.Color(0, 102, 204));
                labelStatus.setText("Aguardando");
                break;
            case 4:
                labelStatus.setForeground(new java.awt.Color(0, 153, 51));
                labelStatus.setText("Aguardando");
                break;
            case 5:
                labelStatus.setForeground(new java.awt.Color(0, 153, 51));
                labelStatus.setText("Efetuada");
                break;
            case 6:
                labelStatus.setForeground(new java.awt.Color(204, 0, 0));
                labelStatus.setText("Cancelada/Recusada");
                break;
            default:
                labelStatus.setText("ERRO");
                sleep(3000);
                dispose();
                break;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTroca = new javax.swing.JTextField();
        labelStatus = new javax.swing.JLabel();
        btnAceitarTroca = new javax.swing.JButton();
        btnRejeitarTroca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Solicitação de Troca");

        jLabel2.setText("Status:");

        txtTroca.setEditable(false);

        labelStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelStatus.setText("LABELSTATUS");

        btnAceitarTroca.setText("Aceitar");

        btnRejeitarTroca.setText("Rejeitar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceitarTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRejeitarTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(labelStatus))
                .addGap(18, 18, 18)
                .addComponent(txtTroca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceitarTroca)
                    .addComponent(btnRejeitarTroca))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceitarTroca;
    private javax.swing.JButton btnRejeitarTroca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JTextField txtTroca;
    // End of variables declaration//GEN-END:variables
}
